### ISSUE TITLE
epic: support for filecoin protocol upgrades

### ISSUE THREAD

**Issue by raulk** [filecoin-project/test-vectors#177]
This issue captures discussion and task breakdown for modelling and supporting Filecoin protocol upgrades in test vectors. To preface the discussion and make sure that we're all on the same page, here's a diagram that summarises the key concepts and establishes a common vocabulary.

![Filecoin Protocol Upgrade Concepts](https://user-images.githubusercontent.com/1101242/95677846-59041c00-0bc0-11eb-8e8a-a2a25e74faad.jpg)

### Modelling network versions in vectors

Since vectors may continue to work across upgrades, my proposal is to add a `variants` array parameter under which we'd record the `(network version, epoch)` tuples a vector can be run with.

With a tvx subcommand, we can run the corpus against a new candidate `(network version, epoch)`, and if the vector completes successfully, we can append in-place the tuple into the `variants` parameter.

This is a space-efficient approach, but it's not immediately obvious from browsing the corpus which vectors are compatible with which upgrade. Alternatively, we could: (1) make the `(network version, epoch)` a single-value parameter, (2) model the upgrade/network name as a top-level folder, and (3) copy over compatible vectors to each folder.

However, this makes everything else really difficult, as the generator and CI jobs now need extra information on where to place each vector they generate.

To support this change, the `epoch` field of the `message` and `tipset` objects will change to `epoch_offset`. The `epoch` in the precondition matrix will serve as an anchor point, and the applies will be performed at offsets from that anchor.

- [x] `precondition/epoch` turns into `precondition/variants` of type `[]{network_version, epoch}`.
- [x] convert epochs in `messages` and `tipsets` to `epoch_offset`, adapt builder DSL.
- [x] `tvx eval [--dry] --nv=4 --epoch=1000 --dir=/path/to/corpus` command to evaluate a corpus against a `(network version, epoch)` tuple, produce a report, and append the tuple in-place to the variants array for all vectors that succeed.
  - went for a different approach; adding a new protocol version is now done by modifying `KnownProtocolVersions`. The generator takes care of the rest.

### Upgrade-named selectors

- [x] Tag each vector with the name of the upgrade that the implementation needs to support in order to handle that vector.

### New migration-class vector

Takes a precondition state tree, applies a migration, produces a postcondition state tree.
Associated tvx tooling.

### Builders

- [x] Adapt the builders so they can record a network version.
- [x] Adapt the builders so we can work with different state tree and actors versions, abstracting the construction of state and messages.
- [x] Add the ability to generate the same functionally-equivalent vector against different versions.

### Parking lot (brainstorm)

- [ ] `tvx migrate` => "upgrade" a vector by applying a migration to the precondition state tree of a vector, executing the applies, saving the postcondition state tree, verifying that the receipt has remained unchanged (for example).
- [ ] workflow: extract from chain, then migrate, then apply workflow.
- [x] constructor mapping/selection based on actors version (or should we always start with v1 and apply migrations?)
- [x] idea: consolidate all variant generation in generator.
